version: 0.2
phases:
  pre_build:
    command:
       - npm install
  build:
    command:
      - npm run build
  post_build:
    command:
      - aws s3 cp index.html s3://112demo/ --region "ap-south-1"
  