version: 0.2
phases:
  pre_build:
    command:
       - npm install
  build:
    command:
      - npm run build
 # post_build:
  #  command:
   #   - aws s3 cp --recursive ./dist s3://112demo/ --region "ap-south-1"
  artifacts:
    files:
      - '**/*'
    discard-paths: no
    base-directory: dist  